services:
  grpc-server:
    build:
      context: .
      dockerfile: docker/grpc-server.Dockerfile
    container_name: sniping-bot-grpc-server
    ports:
      - "50051:50051"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/50051'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - sniping-bot-network
    restart: unless-stopped

  solana-scanner:
    build:
      context: .
      dockerfile: docker/solana-scanner.Dockerfile
    container_name: sniping-bot-solana-scanner
    env_file:
      - .env
    environment:
      # Override gRPC connection to point to the server container
      - SNIPING_BOT_GRPC_HOST=grpc-server
      - SNIPING_BOT_GRPC_PORT=50051
    depends_on:
      - grpc-server
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/grpc-server/50051'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - sniping-bot-network
    restart: unless-stopped

networks:
  sniping-bot-network:
    driver: bridge
