global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # gRPC Server metrics
  - job_name: 'meteora-grpc-server'
    static_configs:
      - targets: ['sniping-bot-grpc-server:9091']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Meteora Scanner metrics
  - job_name: 'meteora-scanner'
    static_configs:
      - targets: ['sniping-bot-solana-scanner:9092']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL metrics (using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics (using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node/System metrics (using node_exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['sniping-bot-node-exporter:9100']
    scrape_interval: 30s
