// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/sniping.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionStatus represents the status of a transaction
type TransactionStatus int32

const (
	TransactionStatus_TRANSACTION_STATUS_UNKNOWN   TransactionStatus = 0
	TransactionStatus_TRANSACTION_STATUS_PENDING   TransactionStatus = 1
	TransactionStatus_TRANSACTION_STATUS_CONFIRMED TransactionStatus = 2
	TransactionStatus_TRANSACTION_STATUS_FINALIZED TransactionStatus = 3
	TransactionStatus_TRANSACTION_STATUS_FAILED    TransactionStatus = 4
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNKNOWN",
		1: "TRANSACTION_STATUS_PENDING",
		2: "TRANSACTION_STATUS_CONFIRMED",
		3: "TRANSACTION_STATUS_FINALIZED",
		4: "TRANSACTION_STATUS_FAILED",
	}
	TransactionStatus_value = map[string]int32{
		"TRANSACTION_STATUS_UNKNOWN":   0,
		"TRANSACTION_STATUS_PENDING":   1,
		"TRANSACTION_STATUS_CONFIRMED": 2,
		"TRANSACTION_STATUS_FINALIZED": 3,
		"TRANSACTION_STATUS_FAILED":    4,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_sniping_proto_enumTypes[0].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_api_proto_sniping_proto_enumTypes[0]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{0}
}

// Transaction represents a Solana transaction
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	ProgramId     string                 `protobuf:"bytes,2,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	Accounts      []string               `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Slot          uint64                 `protobuf:"varint,6,opt,name=slot,proto3" json:"slot,omitempty"`
	Status        TransactionStatus      `protobuf:"varint,7,opt,name=status,proto3,enum=api.sniping.v1.TransactionStatus" json:"status,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_api_proto_sniping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sniping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Transaction) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

func (x *Transaction) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *Transaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Transaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Transaction) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Transaction) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNKNOWN
}

func (x *Transaction) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ProcessTransactionRequest is sent by the scanner to the gRPC server
type ProcessTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	ScannerId     string                 `protobuf:"bytes,2,opt,name=scanner_id,json=scannerId,proto3" json:"scanner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessTransactionRequest) Reset() {
	*x = ProcessTransactionRequest{}
	mi := &file_api_proto_sniping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTransactionRequest) ProtoMessage() {}

func (x *ProcessTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sniping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTransactionRequest.ProtoReflect.Descriptor instead.
func (*ProcessTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ProcessTransactionRequest) GetScannerId() string {
	if x != nil {
		return x.ScannerId
	}
	return ""
}

// ProcessTransactionResponse is the response from processing a transaction
type ProcessTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessTransactionResponse) Reset() {
	*x = ProcessTransactionResponse{}
	mi := &file_api_proto_sniping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTransactionResponse) ProtoMessage() {}

func (x *ProcessTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sniping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTransactionResponse.ProtoReflect.Descriptor instead.
func (*ProcessTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessTransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// GetTransactionHistoryRequest requests historical transaction data
type GetTransactionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramId     string                 `protobuf:"bytes,1,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryRequest) Reset() {
	*x = GetTransactionHistoryRequest{}
	mi := &file_api_proto_sniping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryRequest) ProtoMessage() {}

func (x *GetTransactionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sniping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionHistoryRequest) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

func (x *GetTransactionHistoryRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetTransactionHistoryRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetTransactionHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTransactionHistoryRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// GetTransactionHistoryResponse returns historical transaction data
type GetTransactionHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryResponse) Reset() {
	*x = GetTransactionHistoryResponse{}
	mi := &file_api_proto_sniping_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryResponse) ProtoMessage() {}

func (x *GetTransactionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sniping_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionHistoryResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionHistoryResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetTransactionHistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// SubscribeRequest for subscribing to transaction streams
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramIds    []string               `protobuf:"bytes,1,rep,name=program_ids,json=programIds,proto3" json:"program_ids,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_proto_sniping_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sniping_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeRequest) GetProgramIds() []string {
	if x != nil {
		return x.ProgramIds
	}
	return nil
}

func (x *SubscribeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// TransactionEvent represents a real-time transaction event
type TransactionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionEvent) Reset() {
	*x = TransactionEvent{}
	mi := &file_api_proto_sniping_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEvent) ProtoMessage() {}

func (x *TransactionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sniping_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEvent.ProtoReflect.Descriptor instead.
func (*TransactionEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionEvent) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *TransactionEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TransactionEvent) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

// HealthRequest for health checks
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_sniping_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sniping_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{7}
}

// HealthResponse for health status
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_sniping_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sniping_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// MeteoraPoolInfo represents information about a Meteora pool
type MeteoraPoolInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PoolAddress     string                 `protobuf:"bytes,1,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	TokenAMint      string                 `protobuf:"bytes,2,opt,name=token_a_mint,json=tokenAMint,proto3" json:"token_a_mint,omitempty"`
	TokenBMint      string                 `protobuf:"bytes,3,opt,name=token_b_mint,json=tokenBMint,proto3" json:"token_b_mint,omitempty"`
	TokenASymbol    string                 `protobuf:"bytes,4,opt,name=token_a_symbol,json=tokenASymbol,proto3" json:"token_a_symbol,omitempty"`
	TokenBSymbol    string                 `protobuf:"bytes,5,opt,name=token_b_symbol,json=tokenBSymbol,proto3" json:"token_b_symbol,omitempty"`
	TokenAName      string                 `protobuf:"bytes,6,opt,name=token_a_name,json=tokenAName,proto3" json:"token_a_name,omitempty"`
	TokenBName      string                 `protobuf:"bytes,7,opt,name=token_b_name,json=tokenBName,proto3" json:"token_b_name,omitempty"`
	TokenADecimals  int32                  `protobuf:"varint,8,opt,name=token_a_decimals,json=tokenADecimals,proto3" json:"token_a_decimals,omitempty"`
	TokenBDecimals  int32                  `protobuf:"varint,9,opt,name=token_b_decimals,json=tokenBDecimals,proto3" json:"token_b_decimals,omitempty"`
	CreatorWallet   string                 `protobuf:"bytes,10,opt,name=creator_wallet,json=creatorWallet,proto3" json:"creator_wallet,omitempty"`
	PoolType        string                 `protobuf:"bytes,11,opt,name=pool_type,json=poolType,proto3" json:"pool_type,omitempty"`
	FeeRate         uint64                 `protobuf:"varint,12,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TransactionHash string                 `protobuf:"bytes,14,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	Slot            uint64                 `protobuf:"varint,15,opt,name=slot,proto3" json:"slot,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,16,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MeteoraPoolInfo) Reset() {
	*x = MeteoraPoolInfo{}
	mi := &file_api_proto_sniping_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeteoraPoolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeteoraPoolInfo) ProtoMessage() {}

func (x *MeteoraPoolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sniping_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeteoraPoolInfo.ProtoReflect.Descriptor instead.
func (*MeteoraPoolInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{9}
}

func (x *MeteoraPoolInfo) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

func (x *MeteoraPoolInfo) GetTokenAMint() string {
	if x != nil {
		return x.TokenAMint
	}
	return ""
}

func (x *MeteoraPoolInfo) GetTokenBMint() string {
	if x != nil {
		return x.TokenBMint
	}
	return ""
}

func (x *MeteoraPoolInfo) GetTokenASymbol() string {
	if x != nil {
		return x.TokenASymbol
	}
	return ""
}

func (x *MeteoraPoolInfo) GetTokenBSymbol() string {
	if x != nil {
		return x.TokenBSymbol
	}
	return ""
}

func (x *MeteoraPoolInfo) GetTokenAName() string {
	if x != nil {
		return x.TokenAName
	}
	return ""
}

func (x *MeteoraPoolInfo) GetTokenBName() string {
	if x != nil {
		return x.TokenBName
	}
	return ""
}

func (x *MeteoraPoolInfo) GetTokenADecimals() int32 {
	if x != nil {
		return x.TokenADecimals
	}
	return 0
}

func (x *MeteoraPoolInfo) GetTokenBDecimals() int32 {
	if x != nil {
		return x.TokenBDecimals
	}
	return 0
}

func (x *MeteoraPoolInfo) GetCreatorWallet() string {
	if x != nil {
		return x.CreatorWallet
	}
	return ""
}

func (x *MeteoraPoolInfo) GetPoolType() string {
	if x != nil {
		return x.PoolType
	}
	return ""
}

func (x *MeteoraPoolInfo) GetFeeRate() uint64 {
	if x != nil {
		return x.FeeRate
	}
	return 0
}

func (x *MeteoraPoolInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MeteoraPoolInfo) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *MeteoraPoolInfo) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *MeteoraPoolInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// MeteoraEvent represents a Meteora pool event
type MeteoraEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventType         string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	PoolInfo          *MeteoraPoolInfo       `protobuf:"bytes,2,opt,name=pool_info,json=poolInfo,proto3" json:"pool_info,omitempty"`
	InitialLiquidityA uint64                 `protobuf:"varint,3,opt,name=initial_liquidity_a,json=initialLiquidityA,proto3" json:"initial_liquidity_a,omitempty"`
	InitialLiquidityB uint64                 `protobuf:"varint,4,opt,name=initial_liquidity_b,json=initialLiquidityB,proto3" json:"initial_liquidity_b,omitempty"`
	EventTime         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	Signature         string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MeteoraEvent) Reset() {
	*x = MeteoraEvent{}
	mi := &file_api_proto_sniping_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeteoraEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeteoraEvent) ProtoMessage() {}

func (x *MeteoraEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sniping_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeteoraEvent.ProtoReflect.Descriptor instead.
func (*MeteoraEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{10}
}

func (x *MeteoraEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *MeteoraEvent) GetPoolInfo() *MeteoraPoolInfo {
	if x != nil {
		return x.PoolInfo
	}
	return nil
}

func (x *MeteoraEvent) GetInitialLiquidityA() uint64 {
	if x != nil {
		return x.InitialLiquidityA
	}
	return 0
}

func (x *MeteoraEvent) GetInitialLiquidityB() uint64 {
	if x != nil {
		return x.InitialLiquidityB
	}
	return 0
}

func (x *MeteoraEvent) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *MeteoraEvent) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// ProcessMeteoraEventRequest is sent by the scanner to process Meteora events
type ProcessMeteoraEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeteoraEvent  *MeteoraEvent          `protobuf:"bytes,1,opt,name=meteora_event,json=meteoraEvent,proto3" json:"meteora_event,omitempty"`
	ScannerId     string                 `protobuf:"bytes,2,opt,name=scanner_id,json=scannerId,proto3" json:"scanner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMeteoraEventRequest) Reset() {
	*x = ProcessMeteoraEventRequest{}
	mi := &file_api_proto_sniping_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMeteoraEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMeteoraEventRequest) ProtoMessage() {}

func (x *ProcessMeteoraEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sniping_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMeteoraEventRequest.ProtoReflect.Descriptor instead.
func (*ProcessMeteoraEventRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{11}
}

func (x *ProcessMeteoraEventRequest) GetMeteoraEvent() *MeteoraEvent {
	if x != nil {
		return x.MeteoraEvent
	}
	return nil
}

func (x *ProcessMeteoraEventRequest) GetScannerId() string {
	if x != nil {
		return x.ScannerId
	}
	return ""
}

// ProcessMeteoraEventResponse is the response from processing a Meteora event
type ProcessMeteoraEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMeteoraEventResponse) Reset() {
	*x = ProcessMeteoraEventResponse{}
	mi := &file_api_proto_sniping_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMeteoraEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMeteoraEventResponse) ProtoMessage() {}

func (x *ProcessMeteoraEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sniping_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMeteoraEventResponse.ProtoReflect.Descriptor instead.
func (*ProcessMeteoraEventResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{12}
}

func (x *ProcessMeteoraEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessMeteoraEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessMeteoraEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// GetMeteoraPoolHistoryRequest requests historical Meteora pool data
type GetMeteoraPoolHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAMint    string                 `protobuf:"bytes,1,opt,name=token_a_mint,json=tokenAMint,proto3" json:"token_a_mint,omitempty"`
	TokenBMint    string                 `protobuf:"bytes,2,opt,name=token_b_mint,json=tokenBMint,proto3" json:"token_b_mint,omitempty"`
	CreatorWallet string                 `protobuf:"bytes,3,opt,name=creator_wallet,json=creatorWallet,proto3" json:"creator_wallet,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,7,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeteoraPoolHistoryRequest) Reset() {
	*x = GetMeteoraPoolHistoryRequest{}
	mi := &file_api_proto_sniping_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeteoraPoolHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeteoraPoolHistoryRequest) ProtoMessage() {}

func (x *GetMeteoraPoolHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sniping_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeteoraPoolHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetMeteoraPoolHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{13}
}

func (x *GetMeteoraPoolHistoryRequest) GetTokenAMint() string {
	if x != nil {
		return x.TokenAMint
	}
	return ""
}

func (x *GetMeteoraPoolHistoryRequest) GetTokenBMint() string {
	if x != nil {
		return x.TokenBMint
	}
	return ""
}

func (x *GetMeteoraPoolHistoryRequest) GetCreatorWallet() string {
	if x != nil {
		return x.CreatorWallet
	}
	return ""
}

func (x *GetMeteoraPoolHistoryRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetMeteoraPoolHistoryRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetMeteoraPoolHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMeteoraPoolHistoryRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// GetMeteoraPoolHistoryResponse returns historical Meteora pool data
type GetMeteoraPoolHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pools         []*MeteoraPoolInfo     `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeteoraPoolHistoryResponse) Reset() {
	*x = GetMeteoraPoolHistoryResponse{}
	mi := &file_api_proto_sniping_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeteoraPoolHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeteoraPoolHistoryResponse) ProtoMessage() {}

func (x *GetMeteoraPoolHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sniping_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeteoraPoolHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetMeteoraPoolHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sniping_proto_rawDescGZIP(), []int{14}
}

func (x *GetMeteoraPoolHistoryResponse) GetPools() []*MeteoraPoolInfo {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *GetMeteoraPoolHistoryResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetMeteoraPoolHistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_api_proto_sniping_proto protoreflect.FileDescriptor

const file_api_proto_sniping_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/sniping.proto\x12\x0eapi.sniping.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x03\n" +
	"\vTransaction\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"program_id\x18\x02 \x01(\tR\tprogramId\x12\x1a\n" +
	"\baccounts\x18\x03 \x03(\tR\baccounts\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04slot\x18\x06 \x01(\x04R\x04slot\x129\n" +
	"\x06status\x18\a \x01(\x0e2!.api.sniping.v1.TransactionStatusR\x06status\x12E\n" +
	"\bmetadata\x18\b \x03(\v2).api.sniping.v1.Transaction.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x19ProcessTransactionRequest\x12=\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1b.api.sniping.v1.TransactionR\vtransaction\x12\x1d\n" +
	"\n" +
	"scanner_id\x18\x02 \x01(\tR\tscannerId\"w\n" +
	"\x1aProcessTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\"\xdd\x01\n" +
	"\x1cGetTransactionHistoryRequest\x12\x1d\n" +
	"\n" +
	"program_id\x18\x01 \x01(\tR\tprogramId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\"\x9c\x01\n" +
	"\x1dGetTransactionHistoryResponse\x12?\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1b.api.sniping.v1.TransactionR\ftransactions\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"P\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vprogram_ids\x18\x01 \x03(\tR\n" +
	"programIds\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"\xab\x01\n" +
	"\x10TransactionEvent\x12=\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1b.api.sniping.v1.TransactionR\vtransaction\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x129\n" +
	"\n" +
	"event_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\"\x0f\n" +
	"\rHealthRequest\"\xe5\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12E\n" +
	"\adetails\x18\x03 \x03(\v2+.api.sniping.v1.HealthResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x05\n" +
	"\x0fMeteoraPoolInfo\x12!\n" +
	"\fpool_address\x18\x01 \x01(\tR\vpoolAddress\x12 \n" +
	"\ftoken_a_mint\x18\x02 \x01(\tR\n" +
	"tokenAMint\x12 \n" +
	"\ftoken_b_mint\x18\x03 \x01(\tR\n" +
	"tokenBMint\x12$\n" +
	"\x0etoken_a_symbol\x18\x04 \x01(\tR\ftokenASymbol\x12$\n" +
	"\x0etoken_b_symbol\x18\x05 \x01(\tR\ftokenBSymbol\x12 \n" +
	"\ftoken_a_name\x18\x06 \x01(\tR\n" +
	"tokenAName\x12 \n" +
	"\ftoken_b_name\x18\a \x01(\tR\n" +
	"tokenBName\x12(\n" +
	"\x10token_a_decimals\x18\b \x01(\x05R\x0etokenADecimals\x12(\n" +
	"\x10token_b_decimals\x18\t \x01(\x05R\x0etokenBDecimals\x12%\n" +
	"\x0ecreator_wallet\x18\n" +
	" \x01(\tR\rcreatorWallet\x12\x1b\n" +
	"\tpool_type\x18\v \x01(\tR\bpoolType\x12\x19\n" +
	"\bfee_rate\x18\f \x01(\x04R\afeeRate\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12)\n" +
	"\x10transaction_hash\x18\x0e \x01(\tR\x0ftransactionHash\x12\x12\n" +
	"\x04slot\x18\x0f \x01(\x04R\x04slot\x12I\n" +
	"\bmetadata\x18\x10 \x03(\v2-.api.sniping.v1.MeteoraPoolInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x02\n" +
	"\fMeteoraEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12<\n" +
	"\tpool_info\x18\x02 \x01(\v2\x1f.api.sniping.v1.MeteoraPoolInfoR\bpoolInfo\x12.\n" +
	"\x13initial_liquidity_a\x18\x03 \x01(\x04R\x11initialLiquidityA\x12.\n" +
	"\x13initial_liquidity_b\x18\x04 \x01(\x04R\x11initialLiquidityB\x129\n" +
	"\n" +
	"event_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\"~\n" +
	"\x1aProcessMeteoraEventRequest\x12A\n" +
	"\rmeteora_event\x18\x01 \x01(\v2\x1c.api.sniping.v1.MeteoraEventR\fmeteoraEvent\x12\x1d\n" +
	"\n" +
	"scanner_id\x18\x02 \x01(\tR\tscannerId\"l\n" +
	"\x1bProcessMeteoraEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\"\xa9\x02\n" +
	"\x1cGetMeteoraPoolHistoryRequest\x12 \n" +
	"\ftoken_a_mint\x18\x01 \x01(\tR\n" +
	"tokenAMint\x12 \n" +
	"\ftoken_b_mint\x18\x02 \x01(\tR\n" +
	"tokenBMint\x12%\n" +
	"\x0ecreator_wallet\x18\x03 \x01(\tR\rcreatorWallet\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\a \x01(\tR\x06cursor\"\x92\x01\n" +
	"\x1dGetMeteoraPoolHistoryResponse\x125\n" +
	"\x05pools\x18\x01 \x03(\v2\x1f.api.sniping.v1.MeteoraPoolInfoR\x05pools\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore*\xb6\x01\n" +
	"\x11TransactionStatus\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cTRANSACTION_STATUS_CONFIRMED\x10\x02\x12 \n" +
	"\x1cTRANSACTION_STATUS_FINALIZED\x10\x03\x12\x1d\n" +
	"\x19TRANSACTION_STATUS_FAILED\x10\x042\xea\x05\n" +
	"\x0eSnipingService\x12k\n" +
	"\x12ProcessTransaction\x12).api.sniping.v1.ProcessTransactionRequest\x1a*.api.sniping.v1.ProcessTransactionResponse\x12n\n" +
	"\x13ProcessMeteoraEvent\x12*.api.sniping.v1.ProcessMeteoraEventRequest\x1a+.api.sniping.v1.ProcessMeteoraEventResponse\x12t\n" +
	"\x15GetTransactionHistory\x12,.api.sniping.v1.GetTransactionHistoryRequest\x1a-.api.sniping.v1.GetTransactionHistoryResponse\x12t\n" +
	"\x15GetMeteoraPoolHistory\x12,.api.sniping.v1.GetMeteoraPoolHistoryRequest\x1a-.api.sniping.v1.GetMeteoraPoolHistoryResponse\x12_\n" +
	"\x17SubscribeToTransactions\x12 .api.sniping.v1.SubscribeRequest\x1a .api.sniping.v1.TransactionEvent0\x01\x12\\\n" +
	"\x18SubscribeToMeteoraEvents\x12 .api.sniping.v1.SubscribeRequest\x1a\x1c.api.sniping.v1.MeteoraEvent0\x01\x12P\n" +
	"\x0fGetHealthStatus\x12\x1d.api.sniping.v1.HealthRequest\x1a\x1e.api.sniping.v1.HealthResponseB,Z*github.com/supesu/sniping-bot-v2/api/protob\x06proto3"

var (
	file_api_proto_sniping_proto_rawDescOnce sync.Once
	file_api_proto_sniping_proto_rawDescData []byte
)

func file_api_proto_sniping_proto_rawDescGZIP() []byte {
	file_api_proto_sniping_proto_rawDescOnce.Do(func() {
		file_api_proto_sniping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_sniping_proto_rawDesc), len(file_api_proto_sniping_proto_rawDesc)))
	})
	return file_api_proto_sniping_proto_rawDescData
}

var file_api_proto_sniping_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_sniping_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_sniping_proto_goTypes = []any{
	(TransactionStatus)(0),                // 0: api.sniping.v1.TransactionStatus
	(*Transaction)(nil),                   // 1: api.sniping.v1.Transaction
	(*ProcessTransactionRequest)(nil),     // 2: api.sniping.v1.ProcessTransactionRequest
	(*ProcessTransactionResponse)(nil),    // 3: api.sniping.v1.ProcessTransactionResponse
	(*GetTransactionHistoryRequest)(nil),  // 4: api.sniping.v1.GetTransactionHistoryRequest
	(*GetTransactionHistoryResponse)(nil), // 5: api.sniping.v1.GetTransactionHistoryResponse
	(*SubscribeRequest)(nil),              // 6: api.sniping.v1.SubscribeRequest
	(*TransactionEvent)(nil),              // 7: api.sniping.v1.TransactionEvent
	(*HealthRequest)(nil),                 // 8: api.sniping.v1.HealthRequest
	(*HealthResponse)(nil),                // 9: api.sniping.v1.HealthResponse
	(*MeteoraPoolInfo)(nil),               // 10: api.sniping.v1.MeteoraPoolInfo
	(*MeteoraEvent)(nil),                  // 11: api.sniping.v1.MeteoraEvent
	(*ProcessMeteoraEventRequest)(nil),    // 12: api.sniping.v1.ProcessMeteoraEventRequest
	(*ProcessMeteoraEventResponse)(nil),   // 13: api.sniping.v1.ProcessMeteoraEventResponse
	(*GetMeteoraPoolHistoryRequest)(nil),  // 14: api.sniping.v1.GetMeteoraPoolHistoryRequest
	(*GetMeteoraPoolHistoryResponse)(nil), // 15: api.sniping.v1.GetMeteoraPoolHistoryResponse
	nil,                                   // 16: api.sniping.v1.Transaction.MetadataEntry
	nil,                                   // 17: api.sniping.v1.HealthResponse.DetailsEntry
	nil,                                   // 18: api.sniping.v1.MeteoraPoolInfo.MetadataEntry
	(*timestamppb.Timestamp)(nil),         // 19: google.protobuf.Timestamp
}
var file_api_proto_sniping_proto_depIdxs = []int32{
	19, // 0: api.sniping.v1.Transaction.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: api.sniping.v1.Transaction.status:type_name -> api.sniping.v1.TransactionStatus
	16, // 2: api.sniping.v1.Transaction.metadata:type_name -> api.sniping.v1.Transaction.MetadataEntry
	1,  // 3: api.sniping.v1.ProcessTransactionRequest.transaction:type_name -> api.sniping.v1.Transaction
	19, // 4: api.sniping.v1.GetTransactionHistoryRequest.start_time:type_name -> google.protobuf.Timestamp
	19, // 5: api.sniping.v1.GetTransactionHistoryRequest.end_time:type_name -> google.protobuf.Timestamp
	1,  // 6: api.sniping.v1.GetTransactionHistoryResponse.transactions:type_name -> api.sniping.v1.Transaction
	1,  // 7: api.sniping.v1.TransactionEvent.transaction:type_name -> api.sniping.v1.Transaction
	19, // 8: api.sniping.v1.TransactionEvent.event_time:type_name -> google.protobuf.Timestamp
	19, // 9: api.sniping.v1.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	17, // 10: api.sniping.v1.HealthResponse.details:type_name -> api.sniping.v1.HealthResponse.DetailsEntry
	19, // 11: api.sniping.v1.MeteoraPoolInfo.created_at:type_name -> google.protobuf.Timestamp
	18, // 12: api.sniping.v1.MeteoraPoolInfo.metadata:type_name -> api.sniping.v1.MeteoraPoolInfo.MetadataEntry
	10, // 13: api.sniping.v1.MeteoraEvent.pool_info:type_name -> api.sniping.v1.MeteoraPoolInfo
	19, // 14: api.sniping.v1.MeteoraEvent.event_time:type_name -> google.protobuf.Timestamp
	11, // 15: api.sniping.v1.ProcessMeteoraEventRequest.meteora_event:type_name -> api.sniping.v1.MeteoraEvent
	19, // 16: api.sniping.v1.GetMeteoraPoolHistoryRequest.start_time:type_name -> google.protobuf.Timestamp
	19, // 17: api.sniping.v1.GetMeteoraPoolHistoryRequest.end_time:type_name -> google.protobuf.Timestamp
	10, // 18: api.sniping.v1.GetMeteoraPoolHistoryResponse.pools:type_name -> api.sniping.v1.MeteoraPoolInfo
	2,  // 19: api.sniping.v1.SnipingService.ProcessTransaction:input_type -> api.sniping.v1.ProcessTransactionRequest
	12, // 20: api.sniping.v1.SnipingService.ProcessMeteoraEvent:input_type -> api.sniping.v1.ProcessMeteoraEventRequest
	4,  // 21: api.sniping.v1.SnipingService.GetTransactionHistory:input_type -> api.sniping.v1.GetTransactionHistoryRequest
	14, // 22: api.sniping.v1.SnipingService.GetMeteoraPoolHistory:input_type -> api.sniping.v1.GetMeteoraPoolHistoryRequest
	6,  // 23: api.sniping.v1.SnipingService.SubscribeToTransactions:input_type -> api.sniping.v1.SubscribeRequest
	6,  // 24: api.sniping.v1.SnipingService.SubscribeToMeteoraEvents:input_type -> api.sniping.v1.SubscribeRequest
	8,  // 25: api.sniping.v1.SnipingService.GetHealthStatus:input_type -> api.sniping.v1.HealthRequest
	3,  // 26: api.sniping.v1.SnipingService.ProcessTransaction:output_type -> api.sniping.v1.ProcessTransactionResponse
	13, // 27: api.sniping.v1.SnipingService.ProcessMeteoraEvent:output_type -> api.sniping.v1.ProcessMeteoraEventResponse
	5,  // 28: api.sniping.v1.SnipingService.GetTransactionHistory:output_type -> api.sniping.v1.GetTransactionHistoryResponse
	15, // 29: api.sniping.v1.SnipingService.GetMeteoraPoolHistory:output_type -> api.sniping.v1.GetMeteoraPoolHistoryResponse
	7,  // 30: api.sniping.v1.SnipingService.SubscribeToTransactions:output_type -> api.sniping.v1.TransactionEvent
	11, // 31: api.sniping.v1.SnipingService.SubscribeToMeteoraEvents:output_type -> api.sniping.v1.MeteoraEvent
	9,  // 32: api.sniping.v1.SnipingService.GetHealthStatus:output_type -> api.sniping.v1.HealthResponse
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_proto_sniping_proto_init() }
func file_api_proto_sniping_proto_init() {
	if File_api_proto_sniping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_sniping_proto_rawDesc), len(file_api_proto_sniping_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_sniping_proto_goTypes,
		DependencyIndexes: file_api_proto_sniping_proto_depIdxs,
		EnumInfos:         file_api_proto_sniping_proto_enumTypes,
		MessageInfos:      file_api_proto_sniping_proto_msgTypes,
	}.Build()
	File_api_proto_sniping_proto = out.File
	file_api_proto_sniping_proto_goTypes = nil
	file_api_proto_sniping_proto_depIdxs = nil
}
